---

- name: Install systemd service unit file
  template:
    src: jboss.systemd.j2
    dest: '/etc/systemd/system/{{ jboss__service_name }}.service'
    owner: root
    group: root
    mode: 0640
  register: _jboss__service_systemd
  notify: ['restart-jboss']

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: _jboss__service_systemd is changed
  changed_when: true

- name: Ensure JBoss is started and enabled on boot
  service:
    name: '{{ jboss__service_name }}'
    enabled: '{{ jboss__service_enabled|bool }}'
    state: "{{ jboss__service_enabled|bool|ternary('started', 'stopped') }}"
